default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  cors_allowed_origins: https://ha.xenfo.dev
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1
  login_attempts_threshold: 5
