model_list:
  - model_name: or/openai/gpt-4o
    litellm_params:
      model: openrouter/openai/gpt-4o
      input_cost_per_token: 0.0000025
      output_cost_per_token: 0.00001
  - model_name: or/openai/o3-mini
    litellm_params:
      model: openrouter/openai/o3-mini
      input_cost_per_token: 0.0000011
      output_cost_per_token: 0.0000044
  - model_name: or/anthropic/claude-3.7-sonnet
    litellm_params:
      model: openrouter/anthropic/claude-3.7-sonnet:beta
  - model_name: or/google/gemini-2.0-flash
    litellm_params:
      model: openrouter/google/gemini-2.0-flash-exp:free
      input_cost_per_token: 0
      output_cost_per_token: 0

  - model_name: openai/gpt-4o
    litellm_params:
      model: openai/gpt-4o

  - model_name: anthropic/claude-3.7-sonnet
    litellm_params:
      model: anthropic/claude-3-7-sonnet-20250219

litellm_settings:
  drop_params: true
  # cache: True
